### ISSUE TITLE
Question / Feature: Button title newline support

### ISSUE THREAD

**Issue by adtm** [react-native-segmented-control/segmented-control#116]
### Question / Feature 

Is it possible to have value titles with new lines, sometimes I manage to use the `\t`, but `\n` always jumps the text to a new line and it's not visible.

```
<SegmentedControlIOS
          values={["Some Text \n Some Text "]}
... />
```

![Screenshot 2020-08-04 at 19 44 08](https://user-images.githubusercontent.com/23147325/89320970-f3a92180-d68a-11ea-8929-11d5bd0e6be5.png)

**Comment by zabojad** [comment]
it works in Android but not on iOS... Did you manage to make it work on iOS @adtm ?
