### ISSUE TITLE
Use react-native-test-app for example app

### ISSUE THREAD

**Issue by Naturalclar** [react-native-segmented-control/segmented-control#583]
use [microsoft/react-native-test-app](https://github.com/microsoft/react-native-test-app) for example app

**Comment by hazardemircan** [comment]
@Naturalclar Can you give more informaation please?

**Comment by Naturalclar** [comment]
@hazardemircan sure!
I want to replace the contents in 'example' directory and replace it with react-native-testing-app

An example implementation can be found in this repository 

https://github.com/react-native-menu/menu

**Comment by YajanaRao** [comment]
@Naturalclar I would like to work on this.

**Comment by hazardemircan** [comment]
I would be happy if you give me a chance to try 😊

**Comment by YajanaRao** [comment]
@hazardemircan You can try once. I am getting this error on my system:
https://github.com/microsoft/react-native-test-app/issues/1155

**Comment by hazardemircan** [comment]
> @hazardemircan You can give it a try. I am getting this error on my system: [microsoft/react-native-test-app#1155](https://github.com/microsoft/react-native-test-app/issues/1155)

Thanks, i just fork the repo

**Comment by YajanaRao** [comment]
@Naturalclar @hazardemircan I had to downgrade react native test app to 1.4.6 as we are using react native 0.63 . I am getting few more issue with react native test app 1.4.6 . I will keep you guys updated on this.

This is my fork: https://github.com/YajanaRao/segmented-control/tree/example-react-native-test-app

**Comment by YajanaRao** [comment]
@Naturalclar Here is my PR for this issue: https://github.com/react-native-segmented-control/segmented-control/pull/594
