### ISSUE TITLE
Not behaving same on both iOS and Android.

### ISSUE THREAD

**Issue by yalva** [react-native-segmented-control/segmented-control#75]
# Bug

onChange={event => {
            console.log(event);
          }}

This is giving different results on ios and android.

## Environment info

 "@react-native-community/segmented-control": "^1.4.0",
    "react-native": "0.62.2",

`react-native info` output:

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 18.80 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.npm-global/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 24, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_241 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 1.4.0

## Steps To Reproduce

Just add handler for onChange and log the event.
onChange={event => {
            console.log(event);
          }}

Describe what you expected to happen:

1. Expected to behave same on both ios and android.
2.

## Reproducible sample code

onChange={event => {
            console.log(event);
          }}

**Comment by mrousavy** [comment]
Please give an example of the two outputs. What are the differences?
