### ISSUE TITLE
Dark Theme won't be applied in Android

### ISSUE THREAD

**Issue by exotexot** [react-native-segmented-control/segmented-control#95]
Really enjoy the segmented control! Sadly, the dark-theme won't be applied in the Android version!

**Comment by Naturalclar** [comment]
@exotexot thanks for the comment! currently dark theme isn't applied to android and web, but I'll work on it when I get the chance.
PRs are welcome too :)

**Comment by Andresain123** [comment]
Working on it 🥳
PR soon

**Comment by exotexot** [comment]
@Andresain123 how's it going? :)

**Comment by exotexot** [comment]
bump

**Comment by Andresain123** [comment]
@exotexot Sorry for the delay 😕
I'll finish it tonight or tomorrow morning and open a PR.

![Screenshot_20200918-231507](https://user-images.githubusercontent.com/4752185/93645751-0c845100-fa05-11ea-853d-3f7220184963.png)

**Comment by exotexot** [comment]
No problem at all. Looking really sweet! Nice work @Andresain123
